### ISSUE TITLE
TARS::INT32 not enough

### ISSUE THREAD

**Issue by meijing0114** [TarsPHP/tars-extension#3]
There're developer reporting TARS:INT32 does not work properly. It works at 9 million, but not working when packing 100 million.
Please verify, we should consider border test if this is the case.

**Comment by bobzhangyong** [comment]
暂时不能重现，麻烦联系提供更多信息，或者提供tars 文件

**Comment by meijing0114** [comment]
已经和使用者确认，并无问题。
