### ISSUE TITLE
httpserver encode package and tcp decode failed

### ISSUE THREAD

**Issue by zhaohong-ponyai** [TarsPHP/tars-extension#6]
RequestPacket类中的$_contexts属性，在httpserver进行encode打包后，到tcpserver解包出来，是能读到contenxt，但是读不到context下面的索引

我打日志发现，打出来的key，长度和我自己定义一个变量打出来的不一致，麻烦有空看看哈，帮忙解决一下，谢谢

**Comment by meijing0114** [comment]
感谢反馈，问题已经修复，分支：
https://github.com/TarsPHP/tars-extension/tree/ted/zipkinExamples 
本周内会合并到master

**Comment by zhaohong-ponyai** [comment]
> 感谢反馈，问题已经修复，分支：
> https://github.com/TarsPHP/tars-extension/tree/ted/zipkinExamples
> 本周内会合并到master

你好，我测试过，大概可以用了，不过还有一些可优化的地方哈，比如这个context里面的value值，数据类型全部都是string，希望可以根据实际传入类型返回吧，哈哈，再次感谢！！

**Comment by meijing0114** [comment]
可以说下你们使用除了string之外的场景吗?
现在代码已经合入master。
